# fly.toml app configuration file generated for vroomtv on 2026-06-12T03:13:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vroomtv'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  BASEBALL_DB = '/data/o27v2.db'
  BASEBALL_SYNC_URL = 'https://superinnin.gs/export/db'
  PORT = '8080'
  SYNC_INTERVAL_MIN = '30'
  TENNIS_DB = '/data/tennis.db'
  TENNIS_SYNC_URL = 'https://pctennis.xyz/export/db'
  VIPERBALL_DB = '/data/viperball.db'
  VIPERBALL_SYNC_URL = 'https://viperball.xyz/export/db'

[[mounts]]
  source = 'vroomtv_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
